export enum ROLE_TYPE {
	ADMIN = 'ADMIN',
	DELIVERY_DRIVER = 'DELIVERY_DRIVER',
	DEVELOPER = 'DEVELOPER',
	SHOP_PROVIDER = 'SHOP_PROVIDER',
	SHOP_STAFF = 'SHOP_STAFF'
}

export enum STOCK_TYPE {
	INFINITY = 'INFINITY',
	LIMITED = 'LIMITED',
	OUT = 'OUT',
	INCOMMING = 'INCOMMING'
}

export enum STATUS {
	CREATED = 'CREATED',
	ACCEPTED = 'ACCEPTED',
	ONPROGRESS = 'ONPROGRESS',
	CANCELED_BY_CLIENT = 'CANCELED_BY_CLIENT',
	CANCELED_BY_PROVIDER = 'CANCELED_BY_PROVIDER',
	COMPLETED = 'COMPLETED',
	UNKNOWN = 'UNKNOWN'
}
