export enum ROLE_TYPE {
  ADMIN = 'ADMIN',
  DELIVERY_DRIVER = 'DELIVERY_DRIVER',
  DEVELOPER = 'DEVELOPER',
  SHOP_PROVIDER = 'SHOP_PROVIDER',
  SHOP_STAFF = 'SHOP_STAFF'
}

export enum STOCK_TYPE {
  INFINITY = 'INFINITY',
  LIMITED = 'LIMITED',
  OUT = 'OUT',
  INCOMMING = 'INCOMMING'
}

export enum STATUS {
  ACCEPTED = 'ACCEPTED',
  CREATED = 'CREATED',
  CANCELED_BY_CLIENT = 'CANCELED_BY_CLIENT',
  CANCELED_BY_PROVIDER = 'CANCELED_BY_PROVIDER',
  COMPLETED = 'COMPLETED',
  ONPROGRESS = 'ONPROGRESS',
  ONWAY = 'ONWAY',
  PAYED = 'PAYED',
  PARTIAL_PAYED = 'PARTIAL_PAYED',
  UNKNOWN = 'UNKNOWN',
  WAITING_PAYMENT = 'WAITING_PAYMENT'
}
