export enum ROUTE_NAME {
  AUTH_LOGIN = 'AUTH.LOGIN',
  CATEGORIES = 'DASHBOARD.CATEGORIES',
  HOME = 'DASHBOARD_HOME',
  MESSAGES = 'DASHBOARD.MESSAGES',
  OFFER = 'DASHBOARD.OFFER',
  ORDERS = 'DASHBOARD.ORDERS',
  STORE = 'DASHBOARD.STORE',
  STORES = 'DASHBOARD.STORES',
  STORE_OFFERS = 'DASHBOARD.STORE_OFFERS',
  STORE_ORDERS = 'DASHBOARD.STORE_ORDERS'
}
