export enum ROUTE_NAME {
  AUTH_LOGIN = 'AUTH.LOGIN',
  HOME = 'DASHBOARD_HOME',
  MESSAGES = 'DASHBOARD.MESSAGES',
  OFFERS = 'DASHBOARD.OFFERS',
  ORDERS = 'DASHBOARD.ORDERS',
  STORE = 'DASHBOARD.STORE'
}
